[package]
name = "whep_srt"
description = "WHEP (WebRTC) to SRT"
version = "0.2.1"
edition = "2024"
authors = ["Per Enstedt <per.enstedt@eyevinn.se>"]
exclude = ["docs/*"]

[[bin]]
path = "src/main.rs"
name = "whep-srt"

[dependencies]
gstreamer = "0.25.1"
gst-plugin-webrtc = { version = "0.15.0", features = ["whep"] }

ctrlc = "3.5.2"
clap = { version = "4.6.0", features = ["derive", "env"] }
log = "0.4.29"
env_logger = "0.11.10"

[dev-dependencies]
gst-plugin-webrtchttp = "0.15.0"    #whepsrc
